import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

export type Language = 'es-ES' | 'en-US';
const translations = {
  'es-ES': {
    // Nav & Hero
    'nav.services': 'Servicios', 'nav.ai_features': 'Funciones IA', 'nav.locations': 'Ubicaciones', 'nav.b2b': 'Socios B2B', 'nav.schedule': 'Agendar Cita', 'nav.admin_panel': 'Panel B2B',
    'hero.title': 'La Revolución en el Cuidado de Mascotas es Ahora', 'hero.subtitle': 'Fusionamos tecnología de punta y amor por los animales para ofrecerte una experiencia de bienestar inigualable para tu mascota.', 'hero.cta_main': 'Ver Servicios', 'hero.cta_secondary': 'Explorar IA',
    // Services
    'services.title': 'Autolavado Inteligente: Rápido, Fácil y Divertido', 'services.subtitle': 'Nuestras estaciones de autolavado para perros te ofrecen todo lo necesario para un baño perfecto, sin estrés y con resultados profesionales.',
    'services.basic.title': 'Lavado Básico', 'services.basic.desc': 'Agua tibia, champú hipoalergénico y secador. Lo esencial para una limpieza rápida y efectiva.',
    'services.premium.title': 'Tratamiento Premium', 'services.premium.desc': 'Incluye champú premium, acondicionador revitalizante, y un ciclo de secado avanzado para un pelaje espectacular.',
    'services.spa.title': 'Experiencia Spa', 'services.spa.desc': 'Lo último en relajación para tu mejor amigo. Incluye todo lo del premium más aromaterapia y tratamiento antiestrés.',
    // AI Features
    'ai.title': 'Descubre el Poder de Nuestra Tecnología para Mascotas', 'ai.subtitle': 'Herramientas de inteligencia artificial únicas, diseñadas para entender, asistir y enriquecer la vida de tu compañero fiel.',
    'ai.scanner.title': 'Escáner de Razas', 'ai.scanner.desc': 'Sube una foto y nuestra IA identificará la raza o mezcla de tu perro con una precisión asombrosa.', 'ai.scanner.button': 'Identificar Raza', 'ai.scanner.loading': 'Analizando...',
    'ai.art.title': 'Generador de Arte Canino', 'ai.art.desc': 'Transforma la foto de tu mascota en una obra de arte única. ¡El retrato perfecto para tu hogar o redes sociales!', 'ai.art.button': 'Generar Arte', 'ai.art.loading': 'Creando Magia...', 'ai.art.wait': 'Esto puede tardar un momento...', 'ai.art.success': '¡Tu obra de arte está lista!',
    'ai.chat.title': 'Asistente IA "Conecty"', 'ai.chat.desc': 'Agenda citas, consulta disponibilidad y explora nuestros servicios hablando con nuestro asistente virtual.', 'ai.chat.button': 'Hablar con Asistente', 'ai.chat.welcome_message': '¡Hola! Soy Conecty. Puedo agendar citas, llevarte a secciones de la página o abrir herramientas de IA. ¿Cómo te ayudo?', 'ai.chat.welcome_message_admin': '¡Hola! Soy Conecty, tu asistente de operaciones. ¿Qué datos del sistema necesitas consultar hoy? Puedo darte información sobre clientes, finanzas, marketing o inventario.', 'ai.chat.placeholder': 'Ej: Llévame a la sección de socios...', 'ai.chat.error_message': 'Lo siento, ha ocurrido un error. Por favor, inténtalo de nuevo.', 'ai.chat.new_chat': 'Nuevo Chat', 'ai.chat.mute': 'Silenciar Voz', 'ai.chat.unmute': 'Activar Voz', 'ai.chat.tool_call_booking': '[Confirmando tu cita en el sistema...]', 'ai.chat.tool_call_availability': '[Consultando horarios disponibles...]', 'ai.chat.tool_call_generic': '[Procesando tu solicitud...]',
    // Locations & B2B
    'locations.title': 'Encuentra tu Estación Pet-Tech Más Cercana', 'locations.subtitle': 'Siempre hay una estación cerca de ti. Encuentra la más conveniente en el mapa y visítanos hoy mismo.',
    'b2b.title': 'Únete a la Revolución Pet-Tech como Socio Estratégico', 'b2b.subtitle': 'Ofrecemos soluciones de franquicia y equipamiento de vanguardia para emprendedores y negocios de mascotas. Expande tu oferta de servicios con nuestra tecnología.',
    'b2b.form.title': 'Obtén un Presupuesto Instantáneo con IA', 'b2b.form.name': 'Nombre de la Empresa', 'b2b.form.email': 'Email de Contacto', 'b2b.form.units': 'Número de unidades interesadas', 'b2b.form.cta': 'Generar Presupuesto', 'b2b.form.loading': 'Generando...', 'b2b.form.quote_title': 'Borrador de Presupuesto por IA', 'b2b.form.success_title': '¡Cotización Enviada!', 'b2b.form.success_desc': 'Hemos recibido tu solicitud. Un especialista te contactará pronto.', 'b2b.form.success_cta': 'Solicitar Otra Cotización',
    // Login Page
    'login.title': 'Acceso al Panel B2B', 'login.subtitle': 'Ingresa tus credenciales de administrador.', 'login.password': 'Contraseña', 'login.button': 'Iniciar Sesión', 'login.error': 'Contraseña incorrecta. Inténtalo de nuevo.', 'login.back': 'Volver al inicio',
    // Dashboard
    'dashboard.panel_title': 'Panel B2B',
    'dashboard.nav.summary': 'Resumen', 'dashboard.nav.appointments': 'Citas', 'dashboard.nav.clients': 'Clientes', 'dashboard.nav.leads': 'Leads', 'dashboard.nav.analytics': 'Analíticas', 'dashboard.nav.settings': 'Configuración', 'dashboard.nav.logout': 'Salir al Sitio Público',
    'dashboard.nav.marketing': 'Marketing',
    'dashboard.nav.finances': 'Finanzas', 'dashboard.nav.providers': 'Proveedores', 'dashboard.nav.expenses': 'Gastos', 'dashboard.nav.inventory': 'Inventario',
    'dashboard.summary.title': 'Resumen de Operaciones', 'dashboard.summary.revenue': 'Ingresos (Pagados)', 'dashboard.summary.washes': 'Total de Lavados (Mes)', 'dashboard.summary.alerts': 'Alertas Activas', 'dashboard.summary.new_leads': 'Nuevos Leads',
    'dashboard.google.title': 'Integración con Google Workspace', 'dashboard.google.connect_prompt': 'Conecta tu cuenta de Google para activar la sincronización de datos y copias de seguridad.', 'dashboard.google.connect_prompt_simulation': 'Conecta tu cuenta de Google para sincronizar datos. El administrador debe tener una cuenta de Google Workspace para usar esta función en producción.', 'dashboard.google.connect_button': 'Conectar con Google', 'dashboard.google.disconnect': 'Desconectar cuenta', 'dashboard.google.sync_calendar': 'Sincronizar con Calendar', 'dashboard.google.backup_drive': 'Backup en Drive', 'dashboard.google.export_sheets': 'Exportar a Sheets', 'dashboard.google.syncing': 'Sincronizando...', 'dashboard.google.backing_up': 'Creando copia...', 'dashboard.google.exporting': 'Exportando...',
    'dashboard.google.inserting_events': 'Insertando eventos en el calendario...', 'dashboard.google.uploading_backup': 'Subiendo copia de seguridad a Drive...', 'dashboard.google.creating_sheet': 'Creando hoja de cálculo en Google Sheets...', 'dashboard.google.populating_sheet': 'Escribiendo datos en la hoja de cálculo...',
    'google_popup.title': 'Elige una cuenta', 'google_popup.subtitle': 'para continuar a Pet-Tech Connect', 'google_popup.footer': 'El administrador debe tener una cuenta de Google Workspace para usar esta función en producción.',
    'dashboard.clients.title': 'Gestión de Clientes', 'dashboard.clients.search_placeholder': 'Buscar por nombre de cliente o mascota...', 'dashboard.clients.table_client': 'Cliente', 'dashboard.clients.table_pet': 'Mascota', 'dashboard.clients.table_contact': 'Contacto', 'dashboard.clients.table_member_since': 'Miembro Desde', 'dashboard.clients.pet_sheet_for': 'Ficha de Mascota para', 'dashboard.clients.age': 'Edad', 'dashboard.clients.years': 'años', 'dashboard.clients.weight': 'Peso', 'dashboard.clients.owner': 'Dueño(a)', 'dashboard.clients.medical_history': 'Historial Médico', 'dashboard.clients.vaccine_reminders': 'Recordatorios de Vacunas', 'dashboard.clients.table_actions': 'Acciones', 'dashboard.clients.view_details_button': 'Ver Detalles', 'dashboard.clients.add_appointment_button': 'Agendar Nueva Cita', 'dashboard.clients.communication_log': 'Registro de Comunicación', 'dashboard.clients.add_note_placeholder': 'Añadir nota rápida...', 'dashboard.clients.add_note_button': 'Añadir', 'dashboard.clients.new_appointment_title': 'Nueva Cita para', 'dashboard.clients.form_service': 'Servicio', 'dashboard.clients.form_date': 'Fecha', 'dashboard.clients.form_time': 'Hora', 'dashboard.clients.book_button': 'Confirmar Cita', 'dashboard.clients.filter_all': 'Todos', 'dashboard.clients.filter_recent': 'Recientes', 'dashboard.clients.filter_loyal': 'Leales', 'dashboard.clients.filter_at_risk': 'En Riesgo',
    'dashboard.appointments.title': 'Gestión de Citas', 'dashboard.appointments.filter_all': 'Todas', 'dashboard.appointments.filter_confirmed': 'Confirmadas', 'dashboard.appointments.filter_completed': 'Completadas', 'dashboard.appointments.filter_canceled': 'Canceladas', 'dashboard.appointments.table_date': 'Fecha y Hora', 'dashboard.appointments.table_pet': 'Mascota', 'dashboard.appointments.table_client': 'Cliente', 'dashboard.appointments.table_service': 'Servicio', 'dashboard.appointments.table_status': 'Estado', 'dashboard.appointments.table_payment': 'Pago', 'dashboard.appointments.status_confirmed': 'Confirmada', 'dashboard.appointments.status_completed': 'Completada', 'dashboard.appointments.status_canceled': 'Cancelada', 'dashboard.appointments.payment_status_paid': 'Pagado', 'dashboard.appointments.payment_status_pending': 'Pendiente', 'dashboard.appointments.confirm_payment': 'Confirmar Pago',
    'dashboard.leads.title': 'Gestión de Leads', 'dashboard.leads.table_lead': 'Lead', 'dashboard.leads.table_message': 'Mensaje', 'dashboard.leads.table_date': 'Fecha Captura', 'dashboard.leads.table_status': 'Estado', 'dashboard.leads.status_new': 'Nuevo', 'dashboard.leads.status_contacted': 'Contactado', 'dashboard.leads.status_converted': 'Convertido',
    'dashboard.analytics.title': 'Analíticas de Negocio', 'dashboard.analytics.service_popularity': 'Popularidad de Servicios', 'dashboard.analytics.top_clients': 'Clientes Más Valiosos (Ingresos)', 'dashboard.analytics.peak_hours': 'Horas Pico de Citas',
    'dashboard.marketing.title': 'Centro de Marketing', 'dashboard.marketing.form_title': 'Crear Nueva Promoción', 'dashboard.marketing.form_desc': 'Diseña y envía ofertas especiales a todos tus clientes para impulsar las reservas.', 'dashboard.marketing.promo_title': 'Título de la Promoción', 'dashboard.marketing.promo_desc': 'Descripción (Mensaje para el cliente)', 'dashboard.marketing.promo_discount': 'Descuento (%)', 'dashboard.marketing.send_button': 'Crear y Enviar a todos los Clientes', 'dashboard.marketing.sending': 'Enviando...', 'dashboard.marketing.past_promos_title': 'Promociones Enviadas', 'dashboard.marketing.table_title': 'Título', 'dashboard.marketing.table_discount': 'Descuento', 'dashboard.marketing.table_sent_at': 'Fecha de Envío',
    'dashboard.settings.title': 'Configuración del Sistema',
    'dashboard.settings.payment_title': 'Métodos de Pago', 'dashboard.settings.payment_card': 'Tarjeta de Crédito/Débito', 'dashboard.settings.payment_nfc': 'Pagos sin Contacto (NFC)',
    'dashboard.settings.voice_title': 'Voz de Instrucciones (Autolavado)', 'dashboard.settings.voice_desc': 'Personaliza la voz que guía a los usuarios en las máquinas de autolavado.', 'dashboard.settings.voice_female_es': 'Voz Femenina (Español)', 'dashboard.settings.voice_male_es': 'Voz Masculina (Español)', 'dashboard.settings.voice_celebrity_1': 'Voz de Celebridad (Ej: Morgan Freeman)',
    'dashboard.settings.branding_title': 'Personalización de Marca', 'dashboard.settings.branding_desc': 'Sube tu logo y elige el color principal de tu marca. Estos se reflejarán en tu perfil público.', 'dashboard.settings.upload_logo': 'Subir Logo', 'dashboard.settings.primary_color': 'Color Principal',
    'dashboard.settings.services_title': 'Parámetros de Servicios', 'dashboard.settings.services_desc': 'Ajusta los precios y duraciones de tus servicios de autolavado.', 'dashboard.settings.service_price': 'Precio (COP)', 'dashboard.settings.service_duration': 'Duración (min)', 'dashboard.settings.save_changes': 'Guardar Cambios',
    'dashboard.settings.widget_title': 'Widget de Captura de Leads', 'dashboard.settings.widget_desc': 'Copia y pega este código en tu sitio web para empezar a capturar leads directamente en tu panel de Pet-Tech Connect.', 'dashboard.settings.copy_code': 'Copiar Código', 'dashboard.settings.copied': '¡Copiado!',
    'dashboard.settings.users_title': 'Gestión de Usuarios', 'dashboard.settings.users_desc': 'Invita y gestiona los roles de los miembros de tu equipo.', 'dashboard.settings.invite_user': 'Invitar Usuario', 'dashboard.settings.table_user': 'Usuario', 'dashboard.settings.table_role': 'Rol', 'dashboard.settings.table_last_login': 'Último Acceso', 'dashboard.settings.role_admin': 'Administrador', 'dashboard.settings.role_manager': 'Gestor', 'dashboard.settings.role_employee': 'Empleado',
    'dashboard.settings.deploy_title': 'Zona de Despliegue', 'dashboard.settings.deploy_desc': 'Publica la última versión de tu aplicación para que todos los cambios sean visibles para tus clientes. Este proceso es irreversible.', 'dashboard.settings.deploy_button': 'Desplegar a Producción',
    'dashboard.deploy_modal.title': 'Despliegue en Progreso', 'dashboard.deploy_modal.step_build': 'Compilando assets...', 'dashboard.deploy_modal.step_test': 'Ejecutando pruebas...', 'dashboard.deploy_modal.step_publish': 'Publicando en producción...', 'dashboard.deploy_modal.step_done': '¡Despliegue completado!', 'dashboard.deploy_modal.status_pending': 'Pendiente', 'dashboard.deploy_modal.status_running': 'Ejecutando', 'dashboard.deploy_modal.status_success': 'Éxito', 'dashboard.deploy_modal.close_button': 'Cerrar',
    'dashboard.finances.providers.title': 'Gestión de Proveedores', 'dashboard.finances.providers.table_provider': 'Proveedor', 'dashboard.finances.providers.table_contact': 'Contacto', 'dashboard.finances.providers.table_category': 'Categoría', 'dashboard.finances.category.supplies': 'Suministros', 'dashboard.finances.category.maintenance': 'Mantenimiento', 'dashboard.finances.category.professional_services': 'Servicios Profesionales', 'dashboard.finances.category.other': 'Otro',
    'dashboard.finances.expenses.title': 'Registro de Gastos', 'dashboard.finances.expenses.table_date': 'Fecha', 'dashboard.finances.expenses.table_description': 'Descripción', 'dashboard.finances.expenses.table_category': 'Categoría', 'dashboard.finances.expenses.table_amount': 'Monto', 'dashboard.finances.category.rent': 'Alquiler', 'dashboard.finances.category.utilities': 'Servicios Públicos', 'dashboard.finances.category.marketing': 'Marketing', 'dashboard.finances.category.salaries': 'Salarios',
    'dashboard.finances.inventory.title': 'Control de Inventario', 'dashboard.finances.inventory.table_item': 'Producto', 'dashboard.finances.inventory.table_stock': 'Stock Actual', 'dashboard.finances.inventory.table_threshold': 'Umbral Bajo Stock', 'dashboard.finances.inventory.table_supplier': 'Proveedor', 'dashboard.finances.inventory.status_ok': 'OK', 'dashboard.finances.inventory.status_low': 'Bajo',
    // Footer
    'footer.about': 'Cuidado de mascotas reinventado con tecnología para enriquecer la vida de los animales y sus dueños.', 'footer.links': 'Enlaces Rápidos', 'footer.contact': 'Contacto', 'footer.legal': 'Legal', 'footer.rights': 'Todos los derechos reservados.', 'footer.privacy': 'Política de Privacidad', 'footer.terms': 'Términos de Servicio',
  },
  'en-US': {
    // Nav & Hero
    'nav.services': 'Services', 'nav.ai_features': 'AI Features', 'nav.locations': 'Locations', 'nav.b2b': 'B2B Partners', 'nav.schedule': 'Book Now', 'nav.admin_panel': 'B2B Panel',
    'hero.title': 'The Pet Care Revolution is Now', 'hero.subtitle': 'We merge cutting-edge technology and love for animals to offer an unparalleled wellness experience for your pet.', 'hero.cta_main': 'View Services', 'hero.cta_secondary': 'Explore AI',
    // Services
    'services.title': 'Smart Dog Wash: Fast, Easy, and Fun', 'services.subtitle': 'Our self-service dog wash stations provide everything you need for a perfect bath, stress-free and with professional results.',
    'services.basic.title': 'Basic Wash', 'services.basic.desc': 'Warm water, hypoallergenic shampoo, and a dryer. The essentials for a quick and effective clean.',
    'services.premium.title': 'Premium Treatment', 'services.premium.desc': 'Includes premium shampoo, revitalizing conditioner, and an advanced drying cycle for a spectacular coat.',
    'services.spa.title': 'Spa Experience', 'services.spa.desc': 'The ultimate in relaxation for your best friend. Includes everything from premium plus aromatherapy and anti-stress treatment.',
    // AI Features
    'ai.title': 'Discover the Power of Our Pet Technology', 'ai.subtitle': 'Unique artificial intelligence tools designed to understand, assist, and enrich the life of your faithful companion.',
    'ai.scanner.title': 'Breed Scanner', 'ai.scanner.desc': 'Upload a photo and our AI will identify your dog\'s breed or mix with astonishing accuracy.', 'ai.scanner.button': 'Identify Breed', 'ai.scanner.loading': 'Analyzing...',
    'ai.art.title': 'Canine Art Generator', 'ai.art.desc': 'Transform your pet\'s photo into a unique work of art. The perfect portrait for your home or social media!', 'ai.art.button': 'Create Art', 'ai.art.loading': 'Creating Magic...', 'ai.art.wait': 'This may take a moment...', 'ai.art.success': 'Your artwork is ready!',
    'ai.chat.title': 'AI Assistant "Conecty"', 'ai.chat.desc': 'Book appointments, check availability, and explore our services by talking to our virtual assistant.', 'ai.chat.button': 'Chat with Assistant', 'ai.chat.welcome_message': 'Hi! I\'m Conecty. I can book appointments, take you to site sections, or open AI tools. How can I help you?', 'ai.chat.welcome_message_admin': 'Hi! I\'m Conecty, your operations assistant. What system data do you need to check today? I can provide info on clients, finances, marketing, or inventory.', 'ai.chat.placeholder': 'E.g., Take me to the partners section...', 'ai.chat.error_message': 'I\'m sorry, an error occurred. Please try again.', 'ai.chat.new_chat': 'New Chat', 'ai.chat.mute': 'Mute Voice', 'ai.chat.unmute': 'Unmute Voice', 'ai.chat.tool_call_booking': '[Confirming your appointment in the system...]', 'ai.chat.tool_call_availability': '[Checking available slots...]', 'ai.chat.tool_call_generic': '[Processing your request...]',
    // Locations & B2B
    'locations.title': 'Find Your Nearest Pet-Tech Station', 'locations.subtitle': 'There is always a station near you. Find the most convenient one on the map and visit us today.',
    'b2b.title': 'Join the Pet-Tech Revolution as a Strategic Partner', 'b2b.subtitle': 'We offer cutting-edge franchise and equipment solutions for entrepreneurs and pet businesses. Expand your service offerings with our technology.',
    'b2b.form.title': 'Get an Instant AI-Powered Quote', 'b2b.form.name': 'Company Name', 'b2b.form.email': 'Contact Email', 'b2b.form.units': 'Number of interested units', 'b2b.form.cta': 'Generate Quote', 'b2b.form.loading': 'Generating...', 'b2b.form.quote_title': 'AI-Generated Quote Draft', 'b2b.form.success_title': 'Quote Request Sent!', 'b2b.form.success_desc': 'We have received your request. A specialist will contact you shortly.', 'b2b.form.success_cta': 'Request Another Quote',
    // Login Page
    'login.title': 'B2B Panel Access', 'login.subtitle': 'Enter your administrator credentials.', 'login.password': 'Password', 'login.button': 'Sign In', 'login.error': 'Incorrect password. Please try again.', 'login.back': 'Back to homepage',
    // Dashboard
    'dashboard.panel_title': 'B2B Panel',
    'dashboard.nav.summary': 'Summary', 'dashboard.nav.appointments': 'Appointments', 'dashboard.nav.clients': 'Clients', 'dashboard.nav.leads': 'Leads', 'dashboard.nav.analytics': 'Analytics', 'dashboard.nav.settings': 'Settings', 'dashboard.nav.logout': 'Exit to Public Site',
    'dashboard.nav.marketing': 'Marketing',
    'dashboard.nav.finances': 'Finances', 'dashboard.nav.providers': 'Providers', 'dashboard.nav.expenses': 'Expenses', 'dashboard.nav.inventory': 'Inventory',
    'dashboard.summary.title': 'Operations Summary', 'dashboard.summary.revenue': 'Revenue (Paid)', 'dashboard.summary.washes': 'Total Washes (Month)', 'dashboard.summary.alerts': 'Active Alerts', 'dashboard.summary.new_leads': 'New Leads',
    'dashboard.google.title': 'Google Workspace Integration', 'dashboard.google.connect_prompt': 'Connect your Google account to enable data synchronization and backups.', 'dashboard.google.connect_prompt_simulation': 'Connect your Google account to sync data. The administrator must have a Google Workspace account to use this feature in production.', 'dashboard.google.connect_button': 'Connect with Google', 'dashboard.google.disconnect': 'Disconnect account', 'dashboard.google.sync_calendar': 'Sync to Calendar', 'dashboard.google.backup_drive': 'Backup to Drive', 'dashboard.google.export_sheets': 'Export to Sheets', 'dashboard.google.syncing': 'Syncing...', 'dashboard.google.backing_up': 'Backing up...', 'dashboard.google.exporting': 'Exporting...',
    'dashboard.google.inserting_events': 'Inserting events into Google Calendar...', 'dashboard.google.uploading_backup': 'Uploading backup to Google Drive...', 'dashboard.google.creating_sheet': 'Creating spreadsheet in Google Sheets...', 'dashboard.google.populating_sheet': 'Writing data to the spreadsheet...',
    'google_popup.title': 'Choose an account', 'google_popup.subtitle': 'to continue to Pet-Tech Connect', 'google_popup.footer': 'The administrator must have a Google Workspace account to use this feature in production.',
    'dashboard.clients.title': 'Client Management', 'dashboard.clients.search_placeholder': 'Search by client or pet name...', 'dashboard.clients.table_client': 'Client', 'dashboard.clients.table_pet': 'Pet', 'dashboard.clients.table_contact': 'Contact', 'dashboard.clients.table_member_since': 'Member Since', 'dashboard.clients.pet_sheet_for': 'Pet Sheet for', 'dashboard.clients.age': 'Age', 'dashboard.clients.years': 'years', 'dashboard.clients.weight': 'Weight', 'dashboard.clients.owner': 'Owner', 'dashboard.clients.medical_history': 'Medical History', 'dashboard.clients.vaccine_reminders': 'Vaccine Reminders', 'dashboard.clients.table_actions': 'Actions', 'dashboard.clients.view_details_button': 'View Details', 'dashboard.clients.add_appointment_button': 'Book New Appointment', 'dashboard.clients.communication_log': 'Communication Log', 'dashboard.clients.add_note_placeholder': 'Add a quick note...', 'dashboard.clients.add_note_button': 'Add', 'dashboard.clients.new_appointment_title': 'New Appointment for', 'dashboard.clients.form_service': 'Service', 'dashboard.clients.form_date': 'Date', 'dashboard.clients.form_time': 'Time', 'dashboard.clients.book_button': 'Book Appointment', 'dashboard.clients.filter_all': 'All', 'dashboard.clients.filter_recent': 'Recent', 'dashboard.clients.filter_loyal': 'Loyal', 'dashboard.clients.filter_at_risk': 'At Risk',
    'dashboard.appointments.title': 'Appointment Management', 'dashboard.appointments.filter_all': 'All', 'dashboard.appointments.filter_confirmed': 'Confirmed', 'dashboard.appointments.filter_completed': 'Completed', 'dashboard.appointments.filter_canceled': 'Canceled', 'dashboard.appointments.table_date': 'Date & Time', 'dashboard.appointments.table_pet': 'Pet', 'dashboard.appointments.table_client': 'Client', 'dashboard.appointments.table_service': 'Service', 'dashboard.appointments.table_status': 'Status', 'dashboard.appointments.table_payment': 'Payment', 'dashboard.appointments.status_confirmed': 'Confirmed', 'dashboard.appointments.status_completed': 'Completed', 'dashboard.appointments.status_canceled': 'Canceled', 'dashboard.appointments.payment_status_paid': 'Paid', 'dashboard.appointments.payment_status_pending': 'Pending', 'dashboard.appointments.confirm_payment': 'Confirm Payment',
    'dashboard.leads.title': 'Lead Management', 'dashboard.leads.table_lead': 'Lead', 'dashboard.leads.table_message': 'Message', 'dashboard.leads.table_date': 'Date Captured', 'dashboard.leads.table_status': 'Status', 'dashboard.leads.status_new': 'New', 'dashboard.leads.status_contacted': 'Contacted', 'dashboard.leads.status_converted': 'Converted',
    'dashboard.analytics.title': 'Business Analytics', 'dashboard.analytics.service_popularity': 'Service Popularity', 'dashboard.analytics.top_clients': 'Top Clients (Revenue)', 'dashboard.analytics.peak_hours': 'Peak Appointment Hours',
    'dashboard.marketing.title': 'Marketing Center', 'dashboard.marketing.form_title': 'Create New Promotion', 'dashboard.marketing.form_desc': 'Design and send special offers to all your clients to boost bookings.', 'dashboard.marketing.promo_title': 'Promotion Title', 'dashboard.marketing.promo_desc': 'Description (Message for client)', 'dashboard.marketing.promo_discount': 'Discount (%)', 'dashboard.marketing.send_button': 'Create & Send to all Clients', 'dashboard.marketing.sending': 'Sending...', 'dashboard.marketing.past_promos_title': 'Sent Promotions', 'dashboard.marketing.table_title': 'Title', 'dashboard.marketing.table_discount': 'Discount', 'dashboard.marketing.table_sent_at': 'Date Sent',
    'dashboard.settings.title': 'System Settings',
    'dashboard.settings.payment_title': 'Payment Methods', 'dashboard.settings.payment_card': 'Credit/Debit Card', 'dashboard.settings.payment_nfc': 'Contactless Payments (NFC)',
    'dashboard.settings.voice_title': 'Instruction Voice (Self-Wash)', 'dashboard.settings.voice_desc': 'Customize the voice that guides users at the self-wash machines.', 'dashboard.settings.voice_female_es': 'Female Voice (Spanish)', 'dashboard.settings.voice_male_es': 'Male Voice (Spanish)', 'dashboard.settings.voice_celebrity_1': 'Celebrity Voice (e.g., Morgan Freeman)',
    'dashboard.settings.branding_title': 'Brand Customization', 'dashboard.settings.branding_desc': 'Upload your logo and choose your main brand color. These will be reflected on your public profile.', 'dashboard.settings.upload_logo': 'Upload Logo', 'dashboard.settings.primary_color': 'Primary Color',
    'dashboard.settings.services_title': 'Service Parameters', 'dashboard.settings.services_desc': 'Adjust the prices and durations for your self-wash services.', 'dashboard.settings.service_price': 'Price (COP)', 'dashboard.settings.service_duration': 'Duration (min)', 'dashboard.settings.save_changes': 'Save Changes',
    'dashboard.settings.widget_title': 'Lead Capture Widget', 'dashboard.settings.widget_desc': 'Copy and paste this code onto your website to start capturing leads directly into your Pet-Tech Connect dashboard.', 'dashboard.settings.copy_code': 'Copy Code', 'dashboard.settings.copied': 'Copied!',
    'dashboard.settings.users_title': 'User Management', 'dashboard.settings.users_desc': 'Invite and manage roles for your team members.', 'dashboard.settings.invite_user': 'Invite User', 'dashboard.settings.table_user': 'User', 'dashboard.settings.table_role': 'Role', 'dashboard.settings.table_last_login': 'Last Login', 'dashboard.settings.role_admin': 'Administrator', 'dashboard.settings.role_manager': 'Manager', 'dashboard.settings.role_employee': 'Employee',
    'dashboard.settings.deploy_title': 'Deployment Zone', 'dashboard.settings.deploy_desc': 'Publish the latest version of your application to make all changes visible to your customers. This process is irreversible.', 'dashboard.settings.deploy_button': 'Deploy to Production',
    'dashboard.deploy_modal.title': 'Deployment in Progress', 'dashboard.deploy_modal.step_build': 'Building assets...', 'dashboard.deploy_modal.step_test': 'Running tests...', 'dashboard.deploy_modal.step_publish': 'Publishing to production...', 'dashboard.deploy_modal.step_done': 'Deployment complete!', 'dashboard.deploy_modal.status_pending': 'Pending', 'dashboard.deploy_modal.status_running': 'Running', 'dashboard.deploy_modal.status_success': 'Success', 'dashboard.deploy_modal.close_button': 'Close',
    'dashboard.finances.providers.title': 'Provider Management', 'dashboard.finances.providers.table_provider': 'Provider', 'dashboard.finances.providers.table_contact': 'Contact', 'dashboard.finances.providers.table_category': 'Category', 'dashboard.finances.category.supplies': 'Supplies', 'dashboard.finances.category.maintenance': 'Maintenance', 'dashboard.finances.category.professional_services': 'Professional Services', 'dashboard.finances.category.other': 'Other',
    'dashboard.finances.expenses.title': 'Expense Tracking', 'dashboard.finances.expenses.table_date': 'Date', 'dashboard.finances.expenses.table_description': 'Description', 'dashboard.finances.expenses.table_category': 'Category', 'dashboard.finances.expenses.table_amount': 'Amount', 'dashboard.finances.category.rent': 'Rent', 'dashboard.finances.category.utilities': 'Utilities', 'dashboard.finances.category.marketing': 'Marketing', 'dashboard.finances.category.salaries': 'Salaries',
    'dashboard.finances.inventory.title': 'Inventory Control', 'dashboard.finances.inventory.table_item': 'Item', 'dashboard.finances.inventory.table_stock': 'Current Stock', 'dashboard.finances.inventory.table_threshold': 'Low Stock Threshold', 'dashboard.finances.inventory.table_supplier': 'Supplier', 'dashboard.finances.inventory.status_ok': 'OK', 'dashboard.finances.inventory.status_low': 'Low',
    // Footer
    'footer.about': 'Pet care reinvented with technology to enrich the lives of animals and their owners.', 'footer.links': 'Quick Links', 'footer.contact': 'Contact', 'footer.legal': 'Legal', 'footer.rights': 'All rights reserved.', 'footer.privacy': 'Privacy Policy', 'footer.terms': 'Terms of Service',
  },
};

export type Translations = typeof translations['es-ES'];
interface I18nContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof Translations) => string;
}

const I18nContext = createContext<I18nContextType | undefined>(undefined);

export const I18nProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es-ES');

  useEffect(() => {
    // Optional: Persist language preference
    const savedLang = localStorage.getItem('pet-tech-lang') as Language;
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('pet-tech-lang', lang);
  }

  const t = (key: keyof Translations): string => {
    return translations[language][key] || key;
  };

  return React.createElement(
    I18nContext.Provider,
    { value: { language, setLanguage: handleSetLanguage, t } },
    children
  );
};

export const useI18n = (): I18nContextType => {
  const context = useContext(I18nContext);
  if (!context) {
    throw new Error('useI18n must be used within an I18nProvider');
  }
  return context;
};